# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netbird < Formula
  desc "Netbird project."
  homepage "https://netbird.io/"
  version "0.58.2"
  license "BSD3"

  on_macos do
    on_intel do
      url "https://github.com/netbirdio/netbird/releases/download/v0.58.2/netbird_0.58.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "37849c338fd66e1000aa7d3f3b017159fe3152534fc1ff40f7b42a9b7f022aff"

      def install
        bin.install "netbird"
      end
    end
    on_arm do
      url "https://github.com/netbirdio/netbird/releases/download/v0.58.2/netbird_0.58.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "bab3a493094a80597c1b1f38c4d00ebcfd2b1cc884b70285a40bb3cb7238e687"

      def install
        bin.install "netbird"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/netbirdio/netbird/releases/download/v0.58.2/netbird_0.58.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "2ded4cbb4b200768f3327bdf86ad9acfb44ccd21f770cccbae67ecf0e4545ae5"

        def install
          bin.install "netbird"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/netbirdio/netbird/releases/download/v0.58.2/netbird_0.58.2_linux_armv6.tar.gz", using: CurlDownloadStrategy
        sha256 "052afb8b06927c3d2611c6b90bcd28082195fd72f4ece1e37c640bc49e8f2bd8"

        def install
          bin.install "netbird"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/netbirdio/netbird/releases/download/v0.58.2/netbird_0.58.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "d00fa431c9b582e7ccf2d4c663300b93728c007802a986f0fa483e99fdda01bc"

        def install
          bin.install "netbird"
        end
      end
    end
  end

  test do
    system "#{bin}/netbird version"
  end
end
